// <auto-generated />
using System;
using EslOnline.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EslOnline.Infrastructure.Migrations
{
    [DbContext(typeof(EslOnlineDbContext))]
    partial class EslOnlineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EslOnline.Domain.Aggregates.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("BankAccount");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Buildings.Commercial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CellSizeX")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeY")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeZ")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConstructionUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionZ")
                        .HasColumnType("int");

                    b.Property<string>("Rotation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SizeX")
                        .HasColumnType("int");

                    b.Property<int>("SizeZ")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Commercial");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Buildings.CrossRoad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CellSizeX")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeY")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeZ")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConstructionUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionZ")
                        .HasColumnType("int");

                    b.Property<string>("Rotation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SizeX")
                        .HasColumnType("int");

                    b.Property<int>("SizeZ")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("CrossRoad");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Buildings.Home", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CellSizeX")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeY")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeZ")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConstructionUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionZ")
                        .HasColumnType("int");

                    b.Property<string>("Rotation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SizeX")
                        .HasColumnType("int");

                    b.Property<int>("SizeZ")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Home");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Buildings.Industrial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CellSizeX")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeY")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeZ")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConstructionUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionZ")
                        .HasColumnType("int");

                    b.Property<string>("Rotation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SizeX")
                        .HasColumnType("int");

                    b.Property<int>("SizeZ")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Industrial");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Buildings.Microbusiness", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CellSizeX")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeY")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeZ")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConstructionUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionZ")
                        .HasColumnType("int");

                    b.Property<string>("Production")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rotation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SizeX")
                        .HasColumnType("int");

                    b.Property<int>("SizeZ")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Microbusiness");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Buildings.Road", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CellSizeX")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeY")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeZ")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConstructionUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionZ")
                        .HasColumnType("int");

                    b.Property<string>("Rotation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SizeX")
                        .HasColumnType("int");

                    b.Property<int>("SizeZ")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Road");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Buildings.Square", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CellSizeX")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeY")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeZ")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConstructionUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionZ")
                        .HasColumnType("int");

                    b.Property<string>("Rotation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SizeX")
                        .HasColumnType("int");

                    b.Property<int>("SizeZ")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Square");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Buildings.Tawnhall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CellSizeX")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeY")
                        .HasColumnType("int");

                    b.Property<int>("CellSizeZ")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConstructionUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PositionX")
                        .HasColumnType("int");

                    b.Property<int>("PositionZ")
                        .HasColumnType("int");

                    b.Property<string>("Rotation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SizeX")
                        .HasColumnType("int");

                    b.Property<int>("SizeZ")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Tawnhall");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("City");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Goods.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCanContinueContract")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCanRent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCanSell")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("RentPay")
                        .HasColumnType("bigint");

                    b.Property<int>("RentPayPeriod")
                        .HasColumnType("int");

                    b.Property<long>("RentPenalty")
                        .HasColumnType("bigint");

                    b.Property<int>("RentPeriod")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Goods.StackableGoods.StackableGood", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoodType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Volume")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("StackableGood");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Subjects.Citizen", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AlcoholAddiction")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AlcoholIntoxication")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BankruptcyDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BornId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CitizenshipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Cold")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DrugAddiction")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DrugsIntoxication")
                        .HasColumnType("datetime2");

                    b.Property<float>("Health")
                        .HasColumnType("real");

                    b.Property<float>("Hunger")
                        .HasColumnType("real");

                    b.Property<DateTime?>("Injury")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBankrupt")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMissingPerson")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("Stress")
                        .HasColumnType("real");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Citizen");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Subjects.Government", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("BankruptcyDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("HeadGovernmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("HeadRegionAppointment")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBankrupt")
                        .HasColumnType("bit");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Government");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<Guid>("CitizenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GMail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telegram")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("GMail")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Goods.StackableGoods.StackableGood", b =>
                {
                    b.OwnsOne("EslOnline.Domain.ValueObjects.MovableGoodLocation", "MovebleGoodLocation", b1 =>
                        {
                            b1.Property<Guid>("StackableGoodId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("BuildingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("CitizenId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsInFridge")
                                .HasColumnType("bit");

                            b1.Property<Guid?>("RoomId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("VehicleId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("StackableGoodId");

                            b1.ToTable("StackableGood");

                            b1.WithOwner()
                                .HasForeignKey("StackableGoodId");
                        });

                    b.Navigation("MovebleGoodLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Subjects.Citizen", b =>
                {
                    b.OwnsOne("EslOnline.Domain.ValueObjects.CitizenLocation", "Location", b1 =>
                        {
                            b1.Property<Guid>("CitizenId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("BuildingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CitizenMoveMode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("CityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("IsDriver")
                                .HasColumnType("bit");

                            b1.Property<Guid?>("PublicVehicleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("StartMoveDate")
                                .HasColumnType("datetime2");

                            b1.Property<Guid?>("TargetBuildingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("VehicleId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("CitizenId");

                            b1.ToTable("Citizen");

                            b1.WithOwner()
                                .HasForeignKey("CitizenId");
                        });

                    b.OwnsOne("EslOnline.Domain.ValueObjects.JobPosition", "Job", b1 =>
                        {
                            b1.Property<Guid>("CitizenId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("SubjectId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("CitizenId");

                            b1.ToTable("Citizen");

                            b1.WithOwner()
                                .HasForeignKey("CitizenId");
                        });

                    b.Navigation("Job");

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("EslOnline.Domain.Aggregates.Subjects.Government", b =>
                {
                    b.OwnsOne("EslOnline.Domain.Entities.Codex", "Codex", b1 =>
                        {
                            b1.Property<Guid>("GovernmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("CitizenProfitPercentTax")
                                .HasColumnType("int");

                            b1.Property<int>("CompanyProfitPercentTax")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<long>("ElectionRegestrationFee")
                                .HasColumnType("bigint");

                            b1.Property<long>("EnforcmentDepartmentEmployeersSalary")
                                .HasColumnType("bigint");

                            b1.Property<int>("EnforcmentDepartmentMaxEmployeers")
                                .HasColumnType("int");

                            b1.Property<long>("HeadEnforcmentSalary")
                                .HasColumnType("bigint");

                            b1.Property<long>("HeadFinancialSalary")
                                .HasColumnType("bigint");

                            b1.Property<long>("HeadForeignRelationsSalary")
                                .HasColumnType("bigint");

                            b1.Property<long>("HeadJusticeSalary")
                                .HasColumnType("bigint");

                            b1.Property<long>("HeadUrbanSalary")
                                .HasColumnType("bigint");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("ImmunityCivilServants")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsCanRegionLeaderDissolveLegislative")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsCanRegionLeaderSetControlledRegionLeader")
                                .HasColumnType("bit");

                            b1.Property<string>("LeaderPeriod")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LegislatorsCount")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<long>("LegislatorsSalary")
                                .HasColumnType("bigint");

                            b1.Property<long>("RegionHeadSalary")
                                .HasColumnType("bigint");

                            b1.Property<long>("RegistrationCompanyFee")
                                .HasColumnType("bigint");

                            b1.Property<byte[]>("Timestamp")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("rowversion");

                            b1.HasKey("GovernmentId");

                            b1.ToTable("Government");

                            b1.WithOwner()
                                .HasForeignKey("GovernmentId");
                        });

                    b.OwnsOne("EslOnline.Domain.Entities.Currency", "Currency", b1 =>
                        {
                            b1.Property<Guid>("GovernmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("ShortName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<byte[]>("Timestamp")
                                .IsConcurrencyToken()
                                .ValueGeneratedOnAddOrUpdate()
                                .HasColumnType("rowversion");

                            b1.HasKey("GovernmentId");

                            b1.ToTable("Government");

                            b1.WithOwner()
                                .HasForeignKey("GovernmentId");
                        });

                    b.Navigation("Codex")
                        .IsRequired();

                    b.Navigation("Currency")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
